= Contract for rating movies

Smart contract used in https://github.com/andrzej-casper/pixel-rate[the PixelRate application].

[NOTE]
.Relevant testnet details
====

* Contract deploy hash: https://testnet.cspr.live/deploy/aeb426723aa2caba3e1cee39ed7e310cbe052e9e22fd5559407152a374a14d97[aeb426723aa2caba3e1cee39ed7e310cbe052e9e22fd5559407152a374a14d97]
* Contract package hash: https://testnet.cspr.live/contract-package/f9f9b8d9b4319af3bc0f15bbb74e73e9ca00951700db7e138cae970316985bf3[f9f9b8d9b4319af3bc0f15bbb74e73e9ca00951700db7e138cae970316985bf3]
* Hash - version 1: https://testnet.cspr.live/contract/be3d58d00bfe1af1219addce925af80d68ca6bbfad3d00f36ed9cefa2ecc4266[be3d58d00bfe1af1219addce925af80d68ca6bbfad3d00f36ed9cefa2ecc4266]
====

== Requirements

* rust
* make
* gcc

== Building from source

. Install WASM target:
+
[source,bash]
----
$ rustup target add wasm32-unknown-unknown
----

. Run compilation:
+
[source,bash]
----
$ make build-contract
----

You will find compiled smart contract at `./contract/target/wasm32-unknown-unknown/release/contract.wasm`.

== Testing

To run local test suite execute the following command:

[source,bash]
----
$ make test
----

== Example usage

After you compiled this smart contract, it is time to deploy it to Casper network.

[IMPORTANT]
====
In this example we will be:

* Using *CLI client* to operate - it can be installed with `$ cargo install casper-client`.
* Operating in test chain called *testnet* - specifed in `--chain-name` parameter.
* Sending commands to the one of https://testnet.cspr.live/tools/peers[connected peers] - specified in `--node-address` argument.
* Identify with *account keys* located under `~/wallets/07_alice/` - they were generated with `casper-client keygen [PATH]`.
====

. Deploying smart contract (cost: ~18 CSPR):
+
[source,bash]
----
$ casper-client put-deploy \
  --id 1 \
  --node-address http://135.181.216.142:7777 \
  --chain-name casper-test \
  --secret-key ~/wallets/07_alice/secret_key.pem \
  --payment-amount 18000000000 \
  --session-path ./contract/target/wasm32-unknown-unknown/release/contract.wasm
----

. Getting contract hash:
+
[TIP]
====
Make sure you have `jq` tool installed, as it will be used for JSON parsing. Otherwise you can supply values manually.
====
+
[source,bash]
----
$ STATE_ROOT_HASH=`casper-client get-state-root-hash \
  --id 2 \
  --node-address http://135.181.216.142:7777 \
  | jq -r .result.state_root_hash`
$ casper-client query-global-state \
  --id 3 \
  --node-address http://135.181.216.142:7777 \
  --state-root-hash ${STATE_ROOT_HASH} \
  --key ~/wallets/07_alice/public_key_hex \
  | jq -r ".result.stored_value.Account.named_keys[] | select(.name == \"pixel_rate_contract_hash\") | .key"
hash-be3d58d00bfe1af1219addce925af80d68ca6bbfad3d00f36ed9cefa2ecc4266
----

. Calling contract - rate "The Godfather" movie with 4 stars (cost: ~0.5 CSPR).
+
[NOTE]
====
We will call `rate_movie` entrypoint with 2 arguments:

* movie (string): the-godfather
* rating (u8): 4

Make sure you supplied contract hash (from previous step) to `--session-hash` parameter, but remeber to strip `hash-` prefix.
====
+
[source,bash]
----
$ casper-client put-deploy \
  --id 4 \
  --node-address http://135.181.216.142:7777 \
  --chain-name casper-test \
  --secret-key ~/wallets/07_alice/secret_key.pem \
  --payment-amount 500000000 \
  --session-hash be3d58d00bfe1af1219addce925af80d68ca6bbfad3d00f36ed9cefa2ecc4266 \
  --session-entry-point "rate_movie" \
  --session-arg "movie:string='the-godfather'" \
  --session-arg "rating:u8='4'"
{
  "jsonrpc": "2.0",
  "id": 4,
  "result": {
    "api_version": "1.4.15",
    "deploy_hash": "6b45644df978fcb0ac1c07617b5f9333c3ae733fdf514e5dbbe44280f54d0645"
  }
}
----

. Verify that movie rating was stored:
+
[NOTE]
====
Rating is stored in dictionary named as a movie, and where *key* is the account hash (raw hex, without prefix).

Make sure you supplied contract hash to `--contract-hash` parameter, along with `hash-` prefix.
====
+
[source,bash]
----
$ STATE_ROOT_HASH=`casper-client get-state-root-hash \
  --id 5 \
  --node-address http://135.181.216.142:7777 \
  | jq -r .result.state_root_hash`
$ ACCOUNT_HASH=`casper-client account-address --public-key ~/wallets/07_alice/public_key_hex | cut -d "-" -f3`
$ casper-client get-dictionary-item \
  --id 6 \
  --node-address http://135.181.216.142:7777 \
  --state-root-hash ${STATE_ROOT_HASH} \
  --dictionary-name "the-godfather" \
  --dictionary-item-key ${ACCOUNT_HASH} \
  --contract-hash hash-be3d58d00bfe1af1219addce925af80d68ca6bbfad3d00f36ed9cefa2ecc4266
{
  "jsonrpc": "2.0",
  "id": 6,
  "result": {
    "api_version": "1.4.15",
    "dictionary_key": "dictionary-ae0067c2603625565ce9cc4f32c10590326a97a3bb2b3f712e10a847e89de8f4",
    "stored_value": {
      "CLValue": {
        "cl_type": "U8",
        "bytes": "04",
        "parsed": 4
      }
    },
    "merkle_proof": "[38170 hex chars]"
  }
}
----

As you can see in `.result.stored_value.parsed`, rating `4` was successfully stored.
