= Contract for rating movies

Smart contract used in https://github.com/andrzej-casper/pixel-rate[the PixelRate application].

== Requirements

* rust
* make
* gcc

== Building from source

. Install WASM target:
+
[source,bash]
----
$ rustup target add wasm32-unknown-unknown
----

. Run compilation:
+
[source,bash]
----
$ make build-contract
----


You will find compiled smart contract at `./contract/target/wasm32-unknown-unknown/release/contract.wasm`.

== Testing

To run local test suite execute the following command:

[source,bash]
----
$ make test
----

== Usage

After you compiled this smart contract, it is time to deploy it to Casper network.

In this example we will be:

* Using *CLI client* to operate - it can be installed with `$ cargo install casper-client`.
* Operating in test chain called *testnet* - specifed in `--chain-name` parameter.
* Sending commands to the one of https://testnet.cspr.live/tools/peers[connected peers] - specified in `--node-address` argument.
* Identify with *secret key* located under `~/wallels/07_alice`.

== TODO - notes to cleanup

casper-client put-deploy \
    --node-address http://135.181.216.142:7777 \
    --chain-name casper-test \
    --secret-key ~/Projects/casper/wallets/02_celine/secret_key.pem \
    --payment-amount 37000000000 \
    --session-path ./contract/target/wasm32-unknown-unknown/release/contract.wasm

```
{
  "id": -1734952646104507097,
  "jsonrpc": "2.0",
  "result": {
    "api_version": "1.4.15",
    "deploy_hash": "fdf28a31c081b65674c51760d764fcbfc97f6ca13a1496873b8473fcb5fc1a2f"
  }
}
```

Contract hash:

  hash-1c269b76c5618212a73b482e44c50c414c5bedc57ce0b687f7207307bc17657e

---

casper-client put-deploy \
    --node-address http://135.181.216.142:7777 \
    --chain-name casper-test \
    --secret-key ~/Projects/casper/wallets/02_celine/secret_key.pem \
    --payment-amount 1600000000 \
    --session-hash 1c269b76c5618212a73b482e44c50c414c5bedc57ce0b687f7207307bc17657e \
    --session-entry-point "rate_movie" \
    --session-arg "movie:string='the-godfather'" \
    --session-arg "rating:u8='4'"
{
  "id": -1296089392065216587,
  "jsonrpc": "2.0",
  "result": {
    "api_version": "1.4.15",
    "deploy_hash": "1790d4d63d8d86efbf78e2b84b0236eb62ac2aba3c6110fb76fc6c9a07e9c0df"
  }
}